### ISSUE TITLE
_TZ3210_frm6149r - wrong ota firmware applied

### ISSUE THREAD

**Issue by josephfh** [mdeweerd/zha-toolkit#103]
Apologies if this is the wrong place to report this. Please close if it is.

I (foolishly) sent an ota_notify command to the following LED strip controller using the [zha toolkit](https://github.com/mdeweerd/zha-toolkit) inside Home Assistant. I think it flashed the wrong OTA firmware, as the device now appears as a power switch.

Can I use zha-toolkit to roll back/revert/reset to the previous firmware? I have not been able to find the device's firmware via Google

I reported this issue to the OTA repo here:
https://github.com/Koenkk/zigbee-OTA/issues/174

**Comment by mdeweerd** [comment]
ota_notify is a way to download firmware from Koenkk/zigbee-OTA .

The fact that the device accepts it is actually an issue with the device as it does not verify the proposed software.

zha-toolkit relies on zha which only sends new FW to the device as far as I understand, but I did not look into that in detail

**Comment by josephfh** [comment]
Thanks for the info.
