### ISSUE TITLE
Remote as AlarmControlPanel device type

### ISSUE THREAD

**Issue by mycanaletto** [mdeweerd/zha-toolkit#128]
The zigbee remote controls (Heiman or Woox) are seen as an AlarmControlPanel. This is a choice of the integrators that does not correspond to the use

The problem is that if you want to monitor the events you will find that it sends several in a row and **it is impossible to differentiate them.**

The temporary solution is to process only the first one in single mode and pause it. But this is not a totally reliable solution, especially if you operate several of them...

I tried to change the type :

```
zha:
  device_config:
     a4:c1:38:96:0b:cf:xx:xx-1:
       type: "remote"  # or button
```

It doesn't work

I noticed that under Z2MQTT it works fine as a remote, the behavior is normal and we can process the information correctly.
```

> arm_day_zones
> arm_all_zones
> disarm
> emergency

```

So under ZHA we should be able to choose the operating mode.

I tried to play with clusters or ZhaToolkit without success...

Information and updates welcome...

**Comment by mdeweerd** [comment]
Making the "remotes" work as desired in ZHA possibly requires implementing a quirk for them.

Before that it would be interesting/usefull to see why they are identified as [AlarmControlPanel](https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/alarm_control_panel.py#L81)s.

https://github.com/home-assistant/core/pull/49080 shows what the initial code changes were.

There is quite a big issue on IAS here: https://github.com/zigpy/zigpy/issues/419 .

Possbily the selection as an AlarmControlPanel device is not a bad choice and it likely has to be understood in the full IAS setup, not only as a remote.


zha_toolkit.scan_device can help understand what your device offers - as it is battery powered you may need to wake it up regularly to be able to get replies to all the requests.  I recently added the used of the "tries" parameter to help scan sleepy devices.

**Comment by mycanaletto** [comment]
The problem is not so much that it is seen as an AlarmControlPanel...

- But the fact that it sends several identical events that cannot be filtered...
- But especially if you have another equipment that requires a pin (a keypad for example), disarming the remote control with a button, without being able to enter the pin, creates a trigered on AlarmControlPanel of the remote control... So you can't disarm it...

I made an automation to solve this problem but it's not very clean for an alarm....

https://www.canaletto.fr/post/home-assistant-and-remote-alarm

**Comment by mdeweerd** [comment]
Closing this as I did not manage to find a way how ZHA Toolkit can help.
