### ISSUE TITLE
Logo suggestion

### ISSUE THREAD

**Issue by filmgarage** [mdeweerd/zha-toolkit#140]
What about a new logo for the ZHA toolbox that is more related to the Zitbeen look and feel?

I have the following suggestion:

![logo](https://user-images.githubusercontent.com/30559371/218321225-0f50fd6f-41c8-4635-8101-a3be25e1a37f.png)

What do you think about it?

**Comment by mdeweerd** [comment]
Thanks for proposing a new logo.  It could have been a good start to improve on the current logo but ... 

FYI, [here is what my first proposal looked like](https://github.com/home-assistant/brands/pull/3097/commits/143869aa489972071eb46b2d8e43d35db74d492) and [Frenck's comment](https://github.com/home-assistant/brands/pull/3039#pullrequestreview-842442626) was that brands do not like their logos to be messed with.  Which I agree with, but I did not know what HA's position on that was and many logos do abuse brands in HA IMHO.

If we were strict on the [official guidelines](https://csa-iot.org/wp-content/uploads/2021/12/CSA-Trademark-and-Logo-Usage-Guidelines-05.06.2021.pdf) the Z-word can't even be used at all.

[ZHA reuses the original logo](https://github.com/home-assistant/brands/tree/master/core_integrations/zha) which I think is against the Trademark terms.

This new proposal also reuses the Zigbee logo, so some extra creativity is needed to not mess up or even reuse the original alliance logo.

**Comment by filmgarage** [comment]
Let me see if I can come up with something that might be accepted...

**Comment by filmgarage** [comment]
What about this...?

![logo_toolbox](https://user-images.githubusercontent.com/30559371/218340846-2888bd7f-0939-4e4a-97ba-89a6635c4778.png)

**Comment by mdeweerd** [comment]
It's a direction I think the logo can go into.

The colors remind us what we are playing with.  They are placed as a Z.

Should we not add something to remind that it's about a wireless protocol?  "Waves" around at the ends of (some of) the tools ?

**Comment by filmgarage** [comment]
![logo_radio](https://user-images.githubusercontent.com/30559371/218344458-2a1be773-1b0f-4bda-8e49-b50a02dccdf5.png)

What if the waves resonate from the circle?

**Comment by filmgarage** [comment]
![logo_radio_2](https://user-images.githubusercontent.com/30559371/218344660-25735383-0199-48b6-97a6-cce89ff1fa95.png)

This may be a little bit more sophisticated...

**Comment by filmgarage** [comment]
Or this... :-)
![logo_radio_3](https://user-images.githubusercontent.com/30559371/218344828-d5527992-d836-48a4-8f5e-af28d5edaffb.png)

**Comment by mdeweerd** [comment]
When they move from the center, it looks more like a target shield for arrows and they do not make me think of radio waves.

I was more thinking of this:

![image](https://user-images.githubusercontent.com/1504752/218356510-89dad14b-2730-4dcb-a2de-8b0d5e5fb3aa.png)

![image](https://user-images.githubusercontent.com/1504752/218356367-4a443189-873f-478a-b210-5435bd9a9d8d.png)

**Comment by filmgarage** [comment]
What about this:
![logo_waves](https://user-images.githubusercontent.com/30559371/218414298-b264b614-0ebe-458c-ad00-671b6edb92f5.png)

**Comment by mdeweerd** [comment]
Nice!

Next step is to publish it.  So I'ld need to know how you want to be credited and I'ld like the SVG version for the records (it can be added to a logo subdir) and HA needs two png versions of it (I'll create/optimize them before submitting).

**Comment by mdeweerd** [comment]
Thanks for the new icon and submitting it to ha/brands .

**Comment by mdeweerd** [comment]
The new logo is active 😃

**Comment by mdeweerd** [comment]
The icon propagated well to the HACS and HA UI interfaces.

I was checking if github proposes a method to set an icon for a project.

The closest it proposes is a "Social media preview", which can be defined in the project settings.

They propose this template :
![repository-open-graph-template (2)](https://user-images.githubusercontent.com/1504752/223413645-3e77f596-8cae-44f0-b369-26c4b4c5aa37.png)

I do not know when or where it is shown.

If you want to make a proposal, you're welcome.
