### ISSUE TITLE
Wrong type Init with data16

### ISSUE THREAD

**Issue by lucagessi** [mdeweerd/zha-toolkit#164]
Hi.
I used this integration for test a zigbee device.
I noticed that during data16 attributes write it crashes. In particular utils.py try to create an object data16 which at the end is a list. The list in python cannot be made by int argument so it crashes. Locally I resolved it converting int to bytes array.
Line 607 of utils.py
compare_val = data_type(str2int(attr_val_in))
Breaks. So I just converted attr_val_in to bytes array and it works.
Is it right?

**Comment by mdeweerd** [comment]
Yes, that is correct.

Zigbee has other types to represent integers: int16 and uint16.  'data16' is meant to be a list of bytes.

There are other types that represent sequences of bytes (string, array, octet string) but thos require some kind of indicationf of length, while the data16 type indicates a length of 2 bytes.

If the end devices interprets the two bytes as an integer, then the designer did not select the best type for that attribute.

**Comment by lucagessi** [comment]
I don't understand how you resolved the issue, I don't see any change

**Comment by mdeweerd** [comment]
When I wrote "Yes, that is correct", I meant that the current implementation is correct and therefore "So I just converted attr_val_in to bytes array and it works." is correct.

Your attr_val should be a list of 2 bytes.


So IMHO, there is no issue - I tried to explain what a data16 is - apparently I am not clear.
I can't think of an object where I am sure to find a data16 to test it myself.


Data16 and Bitmap16 are "discrete" types:
![image](https://user-images.githubusercontent.com/1504752/235490720-4f93fe8e-5591-4afc-80b3-617513c823ff.png)
![image](https://user-images.githubusercontent.com/1504752/235490804-2766012c-6b5e-44d6-bb4c-36191e22fa0b.png)

uint16 and int16 are analog types:
![image](https://user-images.githubusercontent.com/1504752/235490922-905256a3-e3c8-40fd-80bc-5c47bd3cba42.png)
![image](https://user-images.githubusercontent.com/1504752/235490957-e012cc44-50ef-4f5d-8ff1-3f4456676b31.png)

enum16 is also discrete:
![image](https://user-images.githubusercontent.com/1504752/235491000-762af55e-cba9-499b-8762-e64c1e340a06.png)

Attribute and cluster ids are discrete types:
![image](https://user-images.githubusercontent.com/1504752/235491294-fdb65573-9eb3-480d-8996-513d5d63ee47.png)

Zigpy asknowledges that data16 is a liste of two bytes (uint8):
https://github.com/zigpy/zigpy/blob/dev/zigpy/types/basic.py#L915-L916

While uint16 and int16 are ints:
### https://github.com/zigpy/zigpy/blob/a7107a1f526d4d2bbce32c047f8fe14f855f5636/zigpy/types/basic.py#L269-L270
https://github.com/zigpy/zigpy/blob/dev/zigpy/types/basic.py#L305-L306

In the first example of attr_wirte, which basically lists all the options, you can see an example of writing an octet string (type 0x41) which is similar to writing a data16 only that you can list as many bytes as you like for an octet string and only 2 for a data16:
https://github.com/mdeweerd/zha-toolkit#attr_write-writeread-an-attribute-value
```yaml
  attr_type: 0x41
  # Example of octet string (the length is added by zha-toolkit)
  attr_val: [41, 33, 8, 45, 52, 46, 50, 191, 55, 57, 136, 60, 100, 102, 63]
```


So there is no issue for me, unless you get an exception or other issue when writing your data16 value like this:

```yaml
  attr_val: [41, 33]
```

If you do not agree, please clarify how you called the service, what you changed (service parameter or code and how).

**Comment by lucagessi** [comment]
Hi.
I try to understand what you said. Sorry but I am a novice of ZigBee and
the way ha and your plugin manage data.
Maybe I wrote in a wrong format the data from ha service. Using write
attribute service from ha gui I simply wrote the integer associated with
data16 and in this way it rise the exception that int is not iterable
(because list constructor do not accept int).
Is there an other way to write data16 value in input control of ha so that
your integration accept it as an array?

Then, in your examples data seems to be formatted as yaml format, there is
an alternative way for using your service a part from ha gui?

**Comment by mdeweerd** [comment]
> Is there an other way to write data16 value in input control of ha so that
your integration accept it as an array?

I suppose that you refer to the entry method in UI mode as opposed to Yaml.

You'll need to enter the value as an array in Yaml, or as a string.  
```
service: zha_toolkit.attr_write
data:
  attr_val: [0x1A,0x02]  # First method
  attr_val: "\x1A\x02"   # Other method (not tested just now, but should work as well)
  ...
```

The methods to use zha-toolkit's services (or methods) are:
- Developer Tools>Services - in UI or Yaml mode (the latter is required to enter an array)
- Automations, scripts by calling a ZHA Toolkit Service (UI or Yaml);
- Call a service [using HA's web api endpoint /api/services/<domain>/service](https://developers.home-assistant.io/docs/api/rest/#:~:text=/api/services/%3Cdomain%3E/%3Cservice%3E);
- Add a user method to zha-toolkit, and call the methods from python.
- [Call a service from python](https://www.home-assistant.io/integrations/python_script#calling-services)


## Convert int to data16 .

To convert your int to data16 you can do the manual conversion `[ value%256, value/256|int ] `.
If you can use a template, you can convert it using HA's [pack filters](https://www.home-assistant.io/docs/configuration/templating/#functions-and-filters-to-process-raw-data).
Zigbee values are usually in little endian order, so you probably need `{{ unpack( value, "<H") }}` to convert value (an unsigned 16 bit integer) into a bytes array using the [templates](https://www.home-assistant.io/docs/configuration/templating/).  You can find 'H' in the [list of format characters](https://docs.python.org/3/library/struct.html#format-characters).

In Developer Tools>Template you can try this to verify that the conversion is as expected.  You can also use it to convert "manually":
```
{% set test_val = pack(0x0102|int,"<H") %}
{{ test_val }}
{{ test_val[0] }}
{{ test_val[1] }}
```

**Comment by lucagessi** [comment]
Hi.
I tried using yaml editor and list format with [x, y]. It works so, you are
right. There is no issue I just was not aware of it.
Thank you for your time!

**Comment by mdeweerd** [comment]
I extended the documentation a bit #165 .
