### ISSUE TITLE
[REQUEST] ZHA Device Exporter command?

### ISSUE THREAD

**Issue by Hedda** [mdeweerd/zha-toolkit#167]
Suggest add ZHA `device_exporter` command/feature for easily exporting lists of Zigbee devices, see dmulcahey's zha-device-exporter:

https://github.com/dmulcahey/zha-device-exporter

https://github.com/dmulcahey/zha-device-exporter/blob/master/custom_components/zha_device_exporter/__init__.py

**Comment by mdeweerd** [comment]
- Do you have some sample output ?
- I could not find "async_get_info" as a function for the moment in zigpy/zigpy-znp .  Does [dmulcahey/zha-device-exporter](https://github.com/dmulcahey/zha-device-exporter) still work?

What already exists:
- [zha_toolkit.zha_devices](https://github.com/mdeweerd/zha-toolkit#zha_devices-device-information-to-event-or-csv) - can write information for all zha devices to CSV;
- [zha_toolkit.scan_device](https://github.com/mdeweerd/zha-toolkit#scan_device-scan-a-deviceread-all-attribute-values) - writes device attributes/commands (when supported) in JSON format.

**Comment by mdeweerd** [comment]
The equivalent features are already available in zha_toolkit.

With the reponse data this is now easier and the [jinja2 to_json filter](https://www.home-assistant.io/docs/configuration/templating/#tofrom-json) make it possible to convert the data to JSON inside a script/automation.
