### ISSUE TITLE
bind_ieee not longer working

### ISSUE THREAD

**Issue by frangigu** [mdeweerd/zha-toolkit#168]
![image](https://github.com/mdeweerd/zha-toolkit/assets/95890417/01e2dd52-3383-4b62-bc6d-89a46c0b9320)
![image](https://github.com/mdeweerd/zha-toolkit/assets/95890417/c7919be8-765f-4283-a07d-7df0e1939175)

Not sure what is causing this issue, it was working properly a couple months ago, tried rolling back from 2023.06.1 to 2023.05.4 without success.

Already bound devices are still reporting as expected.

Only major change I did is switching from channel 15 to 25 a few weeks back.

**Comment by mdeweerd** [comment]
This is likely a change in zigpy - I modified the test verifying if the target is the coordinator.

Released in 0.8.40

**Comment by frangigu** [comment]
Many thanks, that was lightning fast

**Comment by mdeweerd** [comment]
An issue report with enough details helps 😉 .
