### ISSUE TITLE
The robovac custom integration is using deprecated vacuum feature

### ISSUE THREAD

**Issue by ChrisSpray** [mdeweerd/zha-toolkit#193]
The custom integration robovac is extending the deprecated base class VacuumEntity instead of StateVacuumEntity.

This stops working in version 2024.2.0. Please address before upgrading.

**Comment by mdeweerd** [comment]
I looked for "vacuum" in the code (ignoring case) and could not find a single line.

Possibly you are accessing a zigbee device with a quirk that uses this, but I could not find any quirk with that either.

However the home assistant core code does have some references to it - I guess that they'll update the core before it's deprecated.

**Comment by ChrisSpray** [comment]
Thanks for your first look at this.  RoboVac is th only smart vacuum cleaner that I have.
Full log message follows (apologies for not supplying this earlier):
Logger: homeassistant.components.vacuum
Source: components/vacuum/__init__.py:399
Integration: Vacuum (documentation, issues)
First occurred: 8 August 2023 at 07:58:37 (1 occurrences)
Last logged: 8 August 2023 at 07:58:37

robovac::RoboVacEntity is extending the deprecated base class VacuumEntity instead of StateVacuumEntity, this is not valid and will be unsupported from Home Assistant 2024.2. Please report it to the author of the 'robovac' custom integration

**Comment by ChrisSpray** [comment]
I also received this:
Logger: homeassistant.components.vacuum
Source: helpers/entity_platform.py:619
Integration: Vacuum (documentation, issues)
First occurred: 8 August 2023 at 07:58:37 (2 occurrences)
Last logged: 8 August 2023 at 07:58:37

Error adding entities for domain vacuum with platform robovac
Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'access_token'

**Comment by pdecat** [comment]
@ChrisSpray I guess you are using the robovac custom integration. If so, see https://github.com/bmccluskey/robovac/pull/34

**Comment by ChrisSpray** [comment]
My sincere apologies mfor raising this issue in the wrong area. Doh!
