### ISSUE TITLE
Leave: Need 'ieee' and command_data

### ISSUE THREAD

**Issue by galmok** [mdeweerd/zha-toolkit#197]
I was trying to use the ZHA: Leave call but it failed with the message:

 ['ValueError("Need \'ieee\' and command_data\'")']

The complete JSON is:

{'zha_toolkit_version': 'v0.9.7', 'zigpy_version': '0.56.2', 'zigpy_rf_version': '0.11.3', 'ieee_org': 'sensor.rela_til_hojre_for_komfur_ac_frequency_4', 'ieee': '00:15:bc:00:2f:xx:xx:xx', 'command': 'leave', 'command_data': None, 'start_time': '2023-08-16T16:12:33.333843+00:00', 'errors': ['ValueError("Need \'ieee\' and command_data\'")'], 'params': {'dir': 0, 'tries': 1, 'expect_reply': True, 'args': [], 'read_before_write': True, 'read_after_write': True}, 'success': False}

In the GUI, there is no option to enter any comman_data.

**Comment by mdeweerd** [comment]
HA is not "perfectly" flexible for defining the GUI interface of services, and in some cases you need to you the 'Yaml' method.

See https://github.com/mdeweerd/zha-toolkit#leave for a yaml example.

However, I think that I can improve the GUI configuration for the 'leave' service, so I am not closing this issue.
