### ISSUE TITLE
Zigbee throwing errors

### ISSUE THREAD

**Issue by boatmon0** [mdeweerd/zha-toolkit#208]
I'm getting this message in the log:

[bellows.zigbee.application] Unexpected message send notification tag: 153

I cannot add a new zigbee device.  Is the problem my choice of controller?  I'm using that combo zigbee and z-wave usb stick .

**Comment by mdeweerd** [comment]
This is related to [zigpy-bellows](https://github.com/zigpy/bellows/issues) - it's not something that zha-toolkit handles.

It could be that the combo is not well supported yet, but you should open an issue on the link above (and check if there is no other open/closed issue that matches this problem).
