### ISSUE TITLE
Unknown error: OTA' object has no attribute '_listeners'' for service call

### ISSUE THREAD

**Issue by Youngblood50** [mdeweerd/zha-toolkit#221]
Cannot trigger fw updates anymore for any device.

Logger: custom_components.zha_toolkit
Source: custom_components/zha_toolkit/__init__.py:817
Integration: 🧰 ZHA Toolkit

Exception ''OTA' object has no attribute '_listeners'' for service call with data '{'zha_toolkit_version': 'v1.1.8', 'zigpy_version': '0.63.4', 'zigpy_rf_version': '0.12.1', 'ieee_org': 'light.lamp_light', 'ieee': 'd0:cf:5e:ff:fe:fc:85:1f', 'command': 'ota_notify', 'command_data': None, 'start_time': '2024-03-08T11:28:06.111063+00:00', 'errors': ['AttributeError("\'OTA\' object has no attribute \'_listeners\'")'], 'params': {'dir': 0, 'tries': 1, 'expect_reply': True, 'args': [], 'read_before_write': True, 'read_after_write': True, 'download': True}, 'PAR': {'cmd_id': None, 'endpoint_id': None, 'dst_endpoint_id': None, 'cluster_id': None, 'attr_id': None, 'attr_type': None, 'attr_val': None, 'code': None, 'min_interval': None, 'max_interval': None, 'reportable_change': None, 'dir': 0, 'manf': None, 'tries': 1, 'expect_reply': True, 'args': [], 'state_id': None, 'state_attr': None, 'state_value_template': None, 'force_update': False, 'allow_create': False, 'event_success': None, 'event_fail': None, 'event_done': None, 'fail_exception': False, 'read_before_write': True, 'read_after_write': True, 'write_if_equal': False, 'csvfile': None, 'csvlabel': None, 'download': True, 'path': None, 'use_cache': False}, 'success': False}'

Core: 2024.3.0
Supervisor: 2024.02.1
OS: 12.0
Frontend: 20240306.0
HACS Integrations Version: 1.34.0
HACS Frontend Version: 20240119163101

**Comment by mdeweerd** [comment]
I have not installed the latest HA version yet - I believe that there is now functionnality for updates from the device details.

Anyway, this probably goes deeper - zigpy/zha is changing its internals so may impact other commands as well.

**Comment by nlincke** [comment]
Hey,

i have the very same problem running "Core: 2024.3.3".
Any idea if you will be able to fix this? I really looking forward for the update functionality... 
... if you need further information, feel free to ask.

**Comment by systemcrash** [comment]
See #225 and PR #226

**Comment by mdeweerd** [comment]
I've integrated the fixes so this should be fixed in the release.
