### ISSUE TITLE
Error: async_get() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by wbyoung** [mdeweerd/zha-toolkit#229]
I'm getting this new error for a `zha_toolkit.attr_read` after updating from `2024.5.5` to `2024.6.0`.

**Comment by Chreece** [comment]
I'm getting this from the following service: 
```
service: zha_toolkit.attr_read
data:
  ieee: |
    {{ states.lock
          | rejectattr('state', 'in', ['unavailable', 'unknown', None])
          | selectattr('entity_id', 'in', area_entities('Eingang'))
          | map(attribute='entity_id')
          | first }}
  cluster: 257
  tries: 3
  attribute: 0
```

**Comment by AlexW75** [comment]
Same Problem here as well with:
Problem started direcly after the update to 2024.6.0 before it worked.

`service: zha_toolkit.attr_read
data:
  ieee: light.licht_mobil_01
  endpoint: 1
  cluster: 1
  attribute: 33`

**Comment by eilandert** [comment]
yes, same here, after update.

**Comment by flohav** [comment]
Hi, I've got the same issue after 2024.6 HA update.

**Comment by eilandert** [comment]
I reverted back to 2024.5.5 and it worked yet again :-)

**Comment by DerekF35** [comment]
here is a commit for `ble_monitor` that addressed the issue in that codebase.

https://github.com/custom-components/ble_monitor/commit/a95ae14a2146ff6db009ef428e8aeb5733c47238

**Comment by DerekF35** [comment]
I don't have much experience with coding for home assistant, but changes found in https://github.com/mdeweerd/zha-toolkit/pull/231 are working for my system on 2024.6.1

**Comment by benniju** [comment]
> I don't have much experience with coding for home assistant, but changes found in #231 are working for my system on 2024.6.1
Yep, your PR also seems to have fixed the issue for me

**Comment by eilandert** [comment]
@mdeweerd can this be merged?
