### ISSUE TITLE
HACS do not ask for upgrade

### ISSUE THREAD

**Issue by CordoWEB** [mdeweerd/zha-toolkit#236]
I have installed [zha-toolkit](https://github.com/mdeweerd/zha-toolkit) v 1.1.10 via HACS.
When i go in HACS, i can see 1.1.11 version but it does not ask me to upgrade to the last version.

Is it normal ?

**Comment by mdeweerd** [comment]
I think that is HACS related.
I had an installation where the update was proposed - but it may not have been 1.1.10 before that as I update that system on a slow basis.

There are already 1200+ downloads of 1.1.11 .

**Comment by CordoWEB** [comment]
All is ok the morning :)

![image](https://github.com/user-attachments/assets/7d83fef5-40b5-47c3-9cca-28f2a66bcbe7)
