### ISSUE TITLE
Error during setup of component zha_toolkit with v1.1.14 upgrade

### ISSUE THREAD

**Issue by travisp** [mdeweerd/zha-toolkit#243]
Upon upgrading to v1.1.14, I immediately received the following error:

```
Error during setup of component zha_toolkit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 660, in async_setup
    await hass.async_add_executor_job(register_services, hass)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 853, in register_services
    hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2515, in async_register
    self._hass.verify_event_loop_thread("hass.services.async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 463, in verify_event_loop_thread
    frame.report_non_thread_safe_operation(what)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'zha_toolkit' calls hass.services.async_register from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassservicesasync_register at custom_components/zha_toolkit/__init__.py, line 853: hass.services.async_register(. Please report it to the author of the 'zha_toolkit' custom integration.
```

**Comment by archite** [comment]
Same here. Frustrating. Reverting the change [here](https://github.com/mdeweerd/zha-toolkit/commit/2fe9507820e82127ac3540d046466beae7ea6880#diff-583ba145d04c99a9ef3eaee73bc0dbfe8122109d7b72871a18de7527e710516dL660) fixed it for me. Looks like too many levels of `async` ;-).

**Comment by DarthSonic** [comment]
Same for me:

```
Logger: homeassistant.setup
Quelle: setup.py:404
Erstmals aufgetreten: 04:03:41 (1 Vorkommnisse)
Zuletzt protokolliert: 04:03:41

Error during setup of component zha_toolkit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 660, in async_setup
    await hass.async_add_executor_job(register_services, hass)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 853, in register_services
    hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2515, in async_register
    self._hass.verify_event_loop_thread("hass.services.async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 463, in verify_event_loop_thread
    frame.report_non_thread_safe_operation(what)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'zha_toolkit' calls hass.services.async_register from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassservicesasync_register at custom_components/zha_toolkit/__init__.py, line 853: hass.services.async_register(. Please report it to the author of the 'zha_toolkit' custom integration.
```

**Comment by kayloehmann** [comment]
> Same here. Frustrating. Reverting the change [here](https://github.com/mdeweerd/zha-toolkit/commit/2fe9507820e82127ac3540d046466beae7ea6880#diff-583ba145d04c99a9ef3eaee73bc0dbfe8122109d7b72871a18de7527e710516dL660) fixed it for me. Looks like too many levels of `async` ;-).
> 
> > Just the single change, nothing else needed.

Reverting did not fix it for me. :-(

**Comment by RenZan** [comment]
same problem for me

**Comment by ALeXXBody** [comment]
same here

**Comment by urosch** [comment]
Same here

**Comment by DarthSonic** [comment]
> > Same here. Frustrating. Reverting the change [here](https://github.com/mdeweerd/zha-toolkit/commit/2fe9507820e82127ac3540d046466beae7ea6880#diff-583ba145d04c99a9ef3eaee73bc0dbfe8122109d7b72871a18de7527e710516dL660) fixed it for me. Looks like too many levels of `async` ;-).
> > > Just the single change, nothing else needed.
> 
> Reverting did not fix it for me. :-(

You have to revert to 1.1.12

**Comment by CordoWEB** [comment]
Same error with 1.1.4 version.
Back to 1.1.3 is OK.
I'm using HA 2024.6.4.

**Comment by dhover** [comment]
#241

**Comment by travisp** [comment]
> How do you guys reverting versions? Selecting versions at "redownload" show me the older ones, but unable to change from the current

I am able to just select the previous version and click the "download" button. The version number appears greyed out, which would make it seem like you can't select it, but you can.

**Comment by CordoWEB** [comment]
![image](https://github.com/user-attachments/assets/a90c60d3-effa-42a8-8812-55f47ca7d857)
You must wait a few seconds before clicking on donwload button ("Télécharger" in french).

**Comment by thelastoth** [comment]
Thanks - actually I can select any version I want, but when I click on them, it "jump back" to the current after a second, so I'm unable to redownload anything but 1.1.14 :/

**Comment by collateral87** [comment]
![image](https://github.com/user-attachments/assets/d055bb90-ebdb-47d4-9183-7da0bdeea7be)

call this and your're good

**Comment by thelastoth** [comment]
> ![image](https://private-user-images.githubusercontent.com/97076257/355701347-d055bb90-ebdb-47d4-9183-7da0bdeea7be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY0MTUsIm5iZiI6MTcyMzAxNjExNSwicGF0aCI6Ii85NzA3NjI1Ny8zNTU3MDEzNDctZDA1NWJiOTAtZWJkYi00N2Q0LTkxODMtN2RhMGJkZWVhN2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3MzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MzkyOGYxNzE5N2UxOGQ3OWE3NGRjYmNiNGNkYzUzNjA3N2NkYzY3ZGQwYTc3MzQ2YzRjNmRlZjk1MGI2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTy395fmv4-Sr3B2wLkvU_SccmhMzujvONpw6ETla1I)
> 
> call this and your're good

Indeed - thanks, it was a very useful tip!

**Comment by eilandert** [comment]
> Thanks - actually I can select any version I want, but when I click on them, it "jump back" to the current after a second, so I'm unable to redownload anything but 1.1.14 :/
> 
> EDIT: seems to be a general HACS issue unfortunately, have to wait for a new release of HACS ( if there is no workaround )

i had the same.  just click on 1.1.13,  it will jump back to 1.1.14 but if you click download it will work for 1,1.13

**Comment by mdeweerd** [comment]
I've refactored some code - hopefully that's fine by the HomeAssistant team's rules.  It start fine for me on 2024.07.4
v1.1.15 is released

**Comment by jsermer** [comment]
> I've refactored some code - hopefully that's fine by the HomeAssistant team's rules. It start fine for me on 2024.07.4 v1.1.15 is released

Still fails for me.  I'm thinking the requirements is a bit malformed (`>=>`):

```
Setup failed for custom integration 'zha_toolkit': Requirements for zha_toolkit not found: ['pytz>=>2016.10'].
```

**Comment by RenZan** [comment]
Enregistreur: homeassistant.setup
Source: setup.py:269
S'est produit pour la première fois: 00:37:20 (1 occurrences)
Dernier enregistrement: 00:37:20

Setup failed for custom integration 'zha_toolkit': Requirements for zha_toolkit not found: ['pytz>=>2016.10'].

same here

**Comment by mdeweerd** [comment]
Right, I did not update using hacs and apparently this is not checked in the ci action - I am updating that.

**Comment by mdeweerd** [comment]
Updated in v1.1.16

**Comment by jsermer** [comment]
works for me now...thanks for the quick fix

**Comment by RenZan** [comment]
I have no longer zha_toolkit actions/services available now it seems.

I will revert back to v1.1.12 in the meantime to see if all is back to normal ^^

**Comment by bbayu123** [comment]
I don't think v1.1.16 completely fixes it. Actions are still not showing up in 2024.8

```
2024-08-08 10:01:20.666 DEBUG (MainThread) [custom_components.zha_toolkit] DEFAULT_OTAU = /config/zigpy_ota
2024-08-08 10:01:20.666 DEBUG (MainThread) [custom_components.zha_toolkit] Setup services from async_setup
2024-08-08 10:01:20.676 WARNING (MainThread) [py.warnings] /config/custom_components/zha_toolkit/__init__.py:660: RuntimeWarning: coroutine 'register_services' was never awaited
  register_services(hass)

```

**Comment by Phobos-7** [comment]
zha_toolkit.attr_read works only in 1.1.13 on HA 2024.8

**Comment by wbyoung** [comment]
I think several of the (distinct) issues listed in this thread may have been resolved in one of the releases leading up to the beta 1.1.19 which was released today. Want to give that a shot and report back?

**Comment by RenZan** [comment]
> I think several of the (distinct) issues listed in this thread may have been resolved in one of the releases leading up to the beta 1.1.19 which was released today. Want to give that a shot and report back?

I tested v1.1.19 and attr_write is working fine now.

**Comment by bbayu123** [comment]
1.1.19 is working for me as well.

**Comment by mdeweerd** [comment]
Thank you for the feedback.  I am closing this issue.
