### ISSUE TITLE
v.1.1.16 - Service not found for call_service at pos 1: Action zha_toolkit.attr_read not found

### ISSUE THREAD

**Issue by thelastoth** [mdeweerd/zha-toolkit#248]
After updating HA to 24.8, and jumping to toolkit v16 this morning from v12 ( v14 was causing issues past days ), I got the error message in title.

**Comment by jonathanmend33** [comment]
Same bug here (updating HA to 24.8, and jumping to toolkit v16 this morning from v12).
Service "zha_toolkit.attr_read not found"

**Comment by CordoWEB** [comment]
Same bug here on HA 2024.6.4.

**Comment by Mrtnvw** [comment]
Same bug here after upgrading from V1.1.12 > .14, remains at .16.

**Comment by gravymaker17** [comment]
Also seeing a similar error on .16  when triggering a script of mine that calls the zha_toolkit.execute method.

**Comment by wbyoung** [comment]
Try out the beta release, 1.1.19 and see how things go. This resolved all issues for my use cases.

**Comment by gravymaker17** [comment]
This resolved my issue, thanks!

**Comment by Zaleo80** [comment]
1.1.19
Action zha_toolkit.attr_read not found.

1.1.21 (Pre-release)
Action zha_toolkit.attr_read not found.

Maybe this has to do with the fact the services are renamed to actions (Just a wild guess)

**Comment by thelastoth** [comment]
With the new release - 2024.9.0 - the same issue came back unfortunately.

**Comment by mdeweerd** [comment]
I suppose that this is fixed with the updates this week.  Closing.

**Comment by Anthranilic** [comment]
I'm running to a similar issue now in v1.1.26: "Action zha_toolkit.bindings_get not found." when trying to perform an action under developer tools.

**Comment by mdeweerd** [comment]
@Anthranilic I think you made a typo:

![Image](https://github.com/user-attachments/assets/13c7ef41-f53e-4459-81c3-8cdde5134717)

**Comment by Anthranilic** [comment]
Thank you for responding so quickly! And apologies - yes, I had shared a typo - but not working when corrected either. I get the error "Action zha_toolkit.binds_get not found.":

![Image](https://github.com/user-attachments/assets/1b7b9965-10db-4d4b-bc7c-a06043fa373e)

**Comment by Anthranilic** [comment]
No luck searching for just "binding table" or any zha_toolkit actions. I checked the log file, the only associated lines I see are below:

"""
2025-02-25 12:05:40.743 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2025-02-25 12:05:40.743 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2025-02-25 12:05:40.744 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Service not found for call_service at pos 1: Action zha_toolkit.binds_get not found
2025-02-25 12:05:40.744 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472667442128] Action zha_toolkit.binds_get not found
"""

as well as an earlier notification just acknowledging zha_toolkit was installed:
"""
2025-02-24 20:32:30.615 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zha_toolkit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
"""

Is there anything else more specific I should be looking for? I can't see any other zha_toolkit containing lines, other than similar ones to what I posted above (indicating service not found / action not found errors).

**Comment by mdeweerd** [comment]
Quite strange.  The log suggests zha-toolkit is loaded, but you do not see the services.
Re-install?  Restart?

**Comment by Anthranilic** [comment]
No luck with a reinstall or restart, will try a full HACS reinstall next. Any other information I can provide that might help narrow down the issue?

**Comment by Anthranilic** [comment]
Well... this is embarrassing. I think I should have more closely read the section of the docs titled "Enabling zha-toolkit". 

I had not added "zha_toolkit:" to the configuration.yaml file. I have added it, and am now seeing zha_toolkit actions.

All fixed. Thank you very much for helping me through this.

**Comment by mdeweerd** [comment]
Very well - I prefer that.  I did not suggest this because you did have a mention of zha-toolkit in the home-assistant.log.  Will do in the future though.
