### ISSUE TITLE
Does Home Assistant 2024.8 release renaming/refactoring of "service calls" "actions" affect zha-toolkit?

### ISSUE THREAD

**Issue by Hedda** [mdeweerd/zha-toolkit#255]
Does Home Assistant 2024.8 release renaming/refactoring of "service calls" to "actions" affect zha-toolkit and if so how? See:

* https://developers.home-assistant.io/blog/2024/07/16/service-actions/

and

* https://www.home-assistant.io/blog/2024/08/07/release-20248/#goodbye-service-calls-hello-actions-

also watch explanation from Home Assistant developers why this change from "service calls" to "actions" was done in this video:

* https://www.youtube.com/watch?v=fw_9A8iD1g0

**Comment by mdeweerd** [comment]
As far as the documents in the links to text suggest, there is no need to worry here for developers.  I did not examine the release party video - I am not partying for 2024.8!

**Comment by Hedda** [comment]
FYI, ZHA integration documentation also been updated to reflect that latest version now uses "actions" instead of "service calls":

https://www.home-assistant.io/integrations/zha

https://github.com/home-assistant/home-assistant.io/pull/33835

**Comment by CordoWEB** [comment]
All seems to be OK with ZHA_Toolkit 1.1.19 and HA 2024.8.0
I have build a platform test on RPi5 with this config.

![image](https://github.com/user-attachments/assets/5d2122cc-fb7c-4162-ada4-2afee4829590)

For my "normal HA", i'm still using HA 2024.6.4 and ZHA_Toolkit 1.1.12.
Is it possible to publish a clean version for 2024.7.4 and lower and the new version only for HA 2024.8.0 and higher ?

**Comment by CordoWEB** [comment]
All seems to be OK with ZHA_Toolkit 1.1.19 and HA 2024.8.1 too !

**Comment by mdeweerd** [comment]
Great information!

@CordoWEB For the moment the latest version can only be installed from 2024.8 onwards. Maybe I'll change that for a future version once there is enough confidence it still works for lower versions (it should).
