### ISSUE TITLE
Remove the toolbox icon in the ZHA Toolkit integration component name?

### ISSUE THREAD

**Issue by Hedda** [mdeweerd/zha-toolkit#264]
Recommend remove toolbox icon in the ZHA Toolkit integration component name as it does not follow HA's name standard. See:

* https://github.com/home-assistant/frontend/issues/21630

🧰  icon or no 🧰 icon, that is the question?

Suggest just remove special `\ud83e\uddf0` character in name `"name": "ZHA \ud83e\uddf0 Toolkit",` for manifest.json

```
{
  "domain": "zha_toolkit",
  "name": "ZHA \ud83e\uddf0 Toolkit",
  "codeowners": ["@mdeweerd"],
  "dependencies": ["zha"],
  "documentation": "https://github.com/mdeweerd/zha-toolkit",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/mdeweerd/zha-toolkit/issues",
  "requirements": ["aiofiles>=0.4.0", "pytz>=2016.10"],
  "version": "1.0.0"
}
```

https://github.com/mdeweerd/zha-toolkit/blob/main/custom_components/zha_toolkit/manifest.json

Ping @alexruffell

**Comment by alexruffell** [comment]
@Hedda - I agree the icon should be removed. I actually always mistake it for an old music cassette... showing age here. At least it is no longer before the name where it messed with the sorting, anyhow it is now in the middle and just looks off. Doing away with it is the best option in my opinion - especially if it doesn't follow HA frontend standards.

**Comment by mdeweerd** [comment]
Thanks.  The icon was moved a bit further in one of the integrated PRs - thanks to the author.  I gues this is ok.
