### ISSUE TITLE
[SUGGESTION] Move this zha-toolkit repository to the shared zigpy organization?

### ISSUE THREAD

**Issue by Hedda** [mdeweerd/zha-toolkit#3]
@mdeweerd can I suggest that you consider asking/discussing the possibility of having your zha-toolkit repository moved from https://github.com/mdeweerd/zha-toolkit moved to the zigpy organization @ https://github.com/zigpy/ on GitHub so that the mainstream copy of this repo will stay there become upstream for shared access together by the collective of developers that make up the zigpy organization? 

Note that "organization" is just GitHub's terminology as I understand it is more an informal collaboration between like-minded ZHA and zigpy developers in order to collect ZHA and zigpy projects ín one place and shared access rights, (noting that the zigpy organization on GitHub has no public members and that you must be a member to see who’s a part of that organization, which I am not myself).

https://github.com/zigpy/

Most ZHA related repositories have been moved there over time as a way for like-minded ZHA and zigpy developers that are members of the zigpy organization with yourself included can have shared ownership and access to your zha-toolkit repository and the other projects for collaboration within that community? 

Moving it could potentially also help new ZHA developers take notice of this zha-toolkit project.

Hope that you at least will consider this option and if you think it is a good idea then hoping that you all could come to an agreement that will make everyone happy with you continuing this zha-toolkit repository under the zigpy organization together without getting offended by any ownership conflicts.

PS: Same people who are members of that zigpy organization on GitHub also share another GitHub organization called "zha-ng" (short for "ZHA next-generation"?) which contains additional early experimental projects before they became mature to be moved:

https://github.com/zha-ng

**Comment by mdeweerd** [comment]
Opened discussion https://github.com/zigpy/zigpy/discussions/901 .

**Comment by mdeweerd** [comment]
No real movement here, a discussion is open in the zigpy project, so no need to keep this open here.

**Comment by Hedda** [comment]
@mdeweerd For reference, raised this to the Open Home Foundation via this related roadmap discussion about ZHA and Zigbee:

* https://github.com/OpenHomeFoundation/roadmap/issues/93

You might want to post your other ideas/input there anyway as start is a new start at further shaping/improving Zigbee in HA.
