### ISSUE TITLE
Bug in last release 0.7.23

### ISSUE THREAD

**Issue by WolfRevo** [mdeweerd/zha-toolkit#41]
Hi,

with the update from 0.7.22 to 0.7.23 I get the following error:

```
  File "/config/custom_components/zha_toolkit/utils.py", line 178, in get_radio_version
    import deconz
ModuleNotFoundError: No module named 'deconz'
```

This is a little bit nasty as the toolkit is not working right anymore 😏 reverting back to 0.7.22 fixed the issue for me.

**Comment by mdeweerd** [comment]
Ok tried to detect the deconz module what module are you using?

I check if I can improve this case.

**Comment by WolfRevo** [comment]
Fixed. Yes, I use a decojnz USB stick.

**Comment by mdeweerd** [comment]
Good, the version of zigpy_deconz should now be reported in the event_data !
