### ISSUE TITLE
Debug logging configuration in readme is wrong

### ISSUE THREAD

**Issue by cremor** [mdeweerd/zha-toolkit#48]
When I try to enable debug logging as documented in the readme, HA refuses to restart because of an invalid configuration file. The log file contains this error:

```
2022-03-18 14:58:56 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Invalid config for [logger]: [log] is an invalid option for [logger]. Check: logger->logger->log. (See /config/configuration.yaml, line 56).
```

It looks like it has to be `logs` instead of `log` because this works:

```yaml
logger:
  logs:
    custom_components.zha_toolkit: debug
```

But it looks like this not only enables debug logging for zha_toolkit, but for everything? At least I now also get debug logs for other things, e.g. `[homeassistant.core]`.

Please document how the logging configuration has to look to enable debug logging for zha_toolkit, but leave logging for all other components on default levels.

**Comment by mdeweerd** [comment]
@cremor Thanks for notifying this - I updated the documentation.
