### ISSUE TITLE
Handling Chameleon devices that ZHA dont like.

### ISSUE THREAD

**Issue by MattWestb** [mdeweerd/zha-toolkit#5]
So back to the TS004F is one "normal tuya Zigbee devices".
Its standard mode is one dimmer switch with one EP and mess of cluster.
```
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.DIMMER_SWITCH,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    OnOff.cluster_id,
                    LightLink.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                    Time.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    LevelControl.cluster_id,
                    LightLink.cluster_id,
                ],
            }
        },
```
Firs i was deleting the in on/off and group cluster in the quirk because is not one its not long light or outlet. Later i was finding that group binding of On/off and level cluster was not working but adding the group cluster as is ZHA making it possible adding in groups as one loght.
The OnOff cluster as out is OK but if adding it as one in cluster ZHA is making one light  switch in the GU that is not wanted then its having no output relay or LED drive.

Then we is coming  to mode switching of the device.
By sending 1 to attribute 0x8004 on the out on/off cluster is start sending commands with unicast from it but with "custom values" for click, bobble and hold from button 1 on EP1.
We have found that tuya is casting some magic spells then initiating the device by first reading some attributes and the sending one leave with rejoin and then its sending  device accouterments they is sending the 0x8004 with value 1 to the on/off cluster and its start using EP 2-4.
My problem is that ZHA is cant re reading  the EPs after the device is inseminated.

My test is now sending this commands with your tool but its not working.
I have implanted the custom attribute in tuya INIT and with the right quirk loaded i can reading and sending the attribute on the on/off out cluster. The implementation: https://github.com/zigpy/zha-device-handlers/blob/23a166902e50d5c32019e0d4d32a968715041bb6/zhaquirks/tuya/__init__.py#L857

So i think its little strange ZHA cad sending and receiving the attribute but the tool is not.

By the way its easier saying what is OK with this device then what is not and its not Zigbee certified and 90% of all tuya devices but the problem many users is having them and like getting the 12 "scene commands" working. I like getting both modes working OK so its also possible using it as one good dimmer switch and also sending clicks if the user preferring that.

If i can sending and reading attribute with tool its being easier testing then trying doing it in the quirk code then no one have helping getting it  working only some example that is broken then the syntax is wrong and / or the import is not correct and i cant getting it working then my code knowledge is to low.

Back to code:
```
service: zha_toolkit.attr_read
data:
  endpoint: 1
  cluster: 6
  attribute: 32772
  ieee: 60:a4:23:ff:fe:fd:dc:14
```
is generating error but the device is having one 0x0006 out cluster after the quirk is loaded.
The replace in the quirks is for the moment like this:
```
   replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.NON_COLOR_CONTROLLER,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,  # Is needed for adding group then binding is not working.
                    LightLink.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                    Time.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaSmartRemoteOnOffCluster,
#                    TuyaZBOnOffAttributeCluster,
                    LevelControl.cluster_id,
                    Color.cluster_id,
                    LightLink.cluster_id,
                ],
            },
```
The 2 On/Off cluster types is for normal ONOff with extra attribute and the other with tuya "scene" commands but only one is activated at one time then testing then its not OK having two cluster of same type on one EP in ZIgbee.

Thanks for support and great coding !!

**Comment by mdeweerd** [comment]
The `handle_join` command should reinterrogate the device.

Error regarding attribute read/write:
- Only in_clusters have attributes that you can write to;
- out_clusters can send commands to in_clusters of the same type - this requires binding from the out_cluster to the in_cluster;
- Some out_clusters can "listen" to attribute reports - in that case the in_clusters are bound to out_clusters. For example a temperature out_cluster can receive the temperature from the another device to retrieve a "remote temperature"

In your case, your remote control sends commands (from out_cluster) to lights, etc (to in_clusters).
You can't read an attribute from an out_cluster.

In many cases you'll find that when there is an out_cluster, there is also an in_cluster.  In those cases the in_cluster is often there for configuration or to read current state values.

**Comment by MattWestb** [comment]
Thanks for labeling it as one discussion then its not one or more issues and more brainstorming and luck of knowledge from my side in coding.

You have right **i** cant read or writing on one out cluster, but its looks like HA can reading attributes on them:
```
2022-02-05 15:02:22 DEBUG (MainThread) [zigpy.device] [0x63fe] Extending timeout for 0x2c request
2022-02-05 15:02:23 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=False disable_default_response=False> manufacturer=None tsn=75 command_id=1>
2022-02-05 15:02:23 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] ZCL request 0x0001: []
2022-02-05 15:02:23 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] No handler for cluster command 1
2022-02-05 15:02:23 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=44 command_id=Command.Read_Attributes_rsp>
2022-02-05 15:02:23 DEBUG (MainThread) [homeassistant.components.zha.api] Read attribute for: cluster_id: [6] cluster_type: [out] endpoint_id: [1] attribute: [32772] manufacturer: [None] response: [SwitchMode.Command] failure: [{}],
```
And if sending one data 1 to the same out clusters attribute ZHA is logging:
```
2022-02-05 15:08:54 DEBUG (MainThread) [zigpy.device] [0x63fe] Extending timeout for 0x35 request
2022-02-05 15:08:55 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=False disable_default_response=False> manufacturer=None tsn=77 command_id=0>
2022-02-05 15:08:55 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] ZCL request 0x0000: []
2022-02-05 15:08:55 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] No handler for cluster command 0
2022-02-05 15:08:55 DEBUG (MainThread) [zigpy.zcl] [0x63fe:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=53 command_id=Command.Write_Attributes_rsp>
2022-02-05 15:08:55 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x63FE](TS004F): set: True for attr: 32772 to cluster: 6 for ept: 1 - res: [[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]
2022-02-05 15:08:55 DEBUG (MainThread) [homeassistant.components.zha.api] Set attribute for: cluster_id: [6] cluster_type: [out] endpoint_id: [1] attribute: [32772] value: [True] manufacturer: [None] response: [[[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]]
```
the device is changing working mode and is replaying it have doing it.

Its one sleeper so it getting timeout until i pressing one key.

So its not one normal device its one _tuya Zigbee device_.

I have not trying defining the in OnOff cluster then its not good having it in the system then ZHA is making one light switch in the GUI without function.

**Comment by mdeweerd** [comment]
The fact that ZHA reads it is due to zigpy.

ZHA is clearly adressing the out_cluster, and comparing [the code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/api.py#L675-L684) and the log confirms that.

zigpy's code call on read_raw_attributes which calls on _read_attributes from zcl:
https://github.com/zigpy/zigpy/blob/6aea2b1911aa2041cfe0459180b3538535ff5353/zigpy/zcl/__init__.py#L260-L264

Any numerical value seems to pass there, without regards for the fact that its an out_cluster.

So the way ZHA is doing it, is adressing the in_cluster while the out_cluster was provide.
The way zha_toolkit is doing it, is that it checks if the in_cluster exists and if it does not, it fails.

I can update the code to use the out_cluster reference in case the in_cluster reference is missing and make the request regardless of wheter the in_cluster exists or not.

In my opinion the implementation is too loose with the requirements by accepting to read attributes from an out cluster.

In practice your device likely has an in_cluster.  There should be a new methodology in HA to indicate that your device is not a light, but I haven't digged into that yet.  I believe that this was in the december update.

I would assume that the in_cluster should be added to your quirk, but maybe quirks are not meant to make the device look like a valid zigbee device and this behavior may be a literal quirk inside the implementation of zigpy, which is that out_clusters are assumed to have their in_cluster counter parts.

So probably I should update the code and emit some kind of warning.

**Comment by mdeweerd** [comment]
I did this in v0.7.4c - you probably have to accept beta versions in HACS.

**Comment by mdeweerd** [comment]
In the mean time I added `misc_reinitialize` which is a pretty dirty (white-hat) hack to make zigpy think the device is not initialized.  

`handle_join` is not reinitializing much when the device is already set up in zigpy.

`misc_reinitialize` set several device attributes to None and False so that the zigpy initialisation code will proceed with initialisation.

Hopefully I got them all, and your endpoints will be discovered.

This is a pre-release so should not be visible if you didn't accept beta releases for zha-toolkit.

**Comment by MattWestb** [comment]
Great !!
I was thinking then i have getting reading and writing attribute working OK then trying using "puddlys way" = deleting the device in Zigbe.db and in HA device DB and the ZHA shall being flagged as not initiated but your method sound better also i done need licking the device one more time :-)))

**Comment by mdeweerd** [comment]
I am closing this - if you test it and there is an issue with it, you can reopen another issue.
