### ISSUE TITLE
Equivalent to 're-configure device' in ZHA toolkit?

### ISSUE THREAD

**Issue by HarvsG** [mdeweerd/zha-toolkit#73]
I have to situations where I was to reconfigure a device programmatically.

One is a lightbulb that misbehaves (stops obeying it’s bound switch) and then fixes itself when reconfigured.
The second is a battery powered device in an inaccessible place that I accidentally unbound from the co-ordinator but does send ‘checkin’ requests - so I want to send a re-configure request when I know its awake (when it checks in)

Is there a service call in ZHA-toolkit to call the ZHA ‘reconfigure device’ option?

If so I could build an automation to do this for me.

**Comment by mdeweerd** [comment]
I haven't checked that in detail - the closest method might be a leave with rejoin request.  This is probably something that can be added to ZHA-Toolkit after identifying the method to call.


However, the issue with your battery powered device is that when you see it awake it's already too late: it wakes up, checks if anythiing is pending and goes to sleep again.

In ZHA Toolkit quiet a few commands will use the 'tries' parameter.  For instance you can send the "bind" command until it succeeds (maximum 255 times), or send a reporting configuration command up to 255 times so send a reporting configuration that lets your device wake up more often, then reconfigure and undo the reporting configuration after that.
