### ISSUE TITLE
Error on binds_remove_all

### ISSUE THREAD

**Issue by sorenjacobi** [mdeweerd/zha-toolkit#96]
When trying to remove all binds on a light, I get the following error.

zha_toolkit_version: v0.8.19 
zigpy_version: 0.51.3 
zigpy_rf_version: 0.19.0

```
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'dst_ieee'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/zha_toolkit/__init__.py", line 717, in toolkit_service
    raise handler_exception
  File "/config/custom_components/zha_toolkit/__init__.py", line 681, in toolkit_service
    await handler(
  File "/config/custom_components/zha_toolkit/__init__.py", line 766, in command_handler_default
    await default.default(
  File "/config/custom_components/zha_toolkit/default.py", line 33, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/config/custom_components/zha_toolkit/binds.py", line 418, in binds_remove_all
    raise e
  File "/config/custom_components/zha_toolkit/binds.py", line 361, in binds_remove_all
    dst_ieee = t.EUI64.convert(binding["dst"]["dst_ieee"])
KeyError: 'dst_ieee'
```

**Comment by sorenjacobi** [comment]
The error happened when trying to unbind an IKEA bulb from everything. Might be because the bulb didn't have any bindings. I tried afterwards removing all binds from a switch, which worked successfully and without any errors.

**Comment by mdeweerd** [comment]
I guess that this was a group binding without an ieee address.

The binding that is about to be removed is logged when the log level is set to debug, which you can set by calling the service:
```yaml
service: logger.set_level
data:
  custom_components.zha_toolkit: debug
```

I released a new version that should fix this.

**Comment by MattWestb** [comment]
By Zigbee standard is light automatically reporting to it configured group/s and is not being bonded to some groups or IEEE.

Light controllers is being bonded to groups (not all tuya then its made as lights) and normally not to IEEE (latest IKEA FW is doing the last = wrong) and is normally reporting to it but its one large jungle how different manufacture have making in there devices.

**Comment by mdeweerd** [comment]
@MattWestb Where does a Zigbee specification erquire that a light controller must be bound to a group and not to an IEEE address?
I can't find the reference right now, but as far as I remember it there is a written recommendation to do direct IEEE address bindings up to 3 or 4 devices, and groups above that number to limit traffic.

The advantage of doing IEEE address binding is that there is a better guarantee on the delivery of the notification than with group binding.  So I understand why IKEA prefers direct binding over group binding as it will reduce communication failures.

**Comment by MattWestb** [comment]
I dont have that information but i think you have.
Binding light controllers to one group is making it more flexible and dont need redoing the binding then adding light to the group.
If doing IEEE binding the binding must being redone then adding and deleting light to the controller.
And group cluster is not mandatory on light controller so IEEE must being used if doing it "simple".

Zigbee group broadcast is using passive ack in one "real ZB3" network = if the parent router to the controller is not hearing that all neighbors have repaying the broadcast is resenting the same frame and all other routes is doing the same (i think no Zigbee PRO stack is doing the broadcast 3 time and out).

IKEA latest firmware for 1 and 2 gen controller is one bug and in 3 gen controllers (Styrbar) they is using normal group binding and not IEEE.

I have one tuya double dimmer module that was working with 2 groups and 2 IKEA on/off dimmer bound to the groups and was working great.
After FW upgrade i must doing IEEE binding = both remotes is controlling both endpoints / light and cant dim only on off / device not EP = complete broken !!

I agree with that 3-4 devices is making less traffic but its not is not so flexible as group and its not limited to the 15.4 network broadcast 1.2 frames / second.

**Comment by mdeweerd** [comment]
Flexibility is discussable, with groups you need to add the source and the end device to a group (defined on end device) and not make a direct link between the source and the destination (with the link being defined on the source).

In one case you need to define groups, in the other you do not.

When you define groups, you must be careful to not mix them.  With a direct link you do not need to know what already exists.

So it depends.

Normally when you bind between devices you define the target EP which can be all EPs of the target or just one, but that is a choice.  If it does not work, then that is not compliant with the specification.

Dimming is not the same cluster as on/off - so you must make sure to bine all the clusters you need.

**Comment by mdeweerd** [comment]
Supposing the fix is confirmed, closing.
